parameters:
  - name: publishToNugetOrg
    displayName: Publish to nuget.org?
    type: boolean
    default: false

pr: none
trigger: none

resources:
  pipelines:
    - pipeline: build
      source: connector-sdk.official
      # Only accept builds from release tags or release branches.
      branch:
        include:
          - refs/tags/v*
          - refs/heads/release/*

extends:
  template: /eng/ci/templates/jobs/release-packages.yml@self
  parameters:
    publishToNugetOrg: ${{ parameters.publishToNugetOrg }}
