parameters:
  - name: isReleaseBranchOrTag
    displayName: Is this build from a release branch or release tag?
    type: boolean
    default: false
  - name: publishToNugetOrg
    displayName: Publish to nuget.org? (Only effective when triggered from a release branch or tag)
    type: boolean
    default: false

pr: none
trigger: none

resources:
  pipelines:
    - pipeline: build
      source: connectors-sdk.official

extends:
  template: /eng/ci/templates/jobs/release-packages.yml@self
  parameters:
    isReleaseBranchOrTag: ${{ parameters.isReleaseBranchOrTag }}
    publishToNugetOrg: ${{ and(parameters.isReleaseBranchOrTag, parameters.publishToNugetOrg) }}
